use amazondb;
people = ["Marc", "Bill", "George", "Eliot", "Matt", "Trey", "Tracy", "Greg", "Steve", "Kristina", "Katie", "Jeff"];

totlaCount = 10000000;
numRow = 1000000;
comment="First album I've bought since Napster","We've come a long way since the days of Ninetendo synthesized music! I say without exaggeration that the Chrono Cross Original Soundtrack is probably some of the best instrumental music I've ever heard. Yasunori Mitsuda incorporates so many instruments and musical styles to this collection it's a real credit to his talent. Guitars violins cellos and the piano are just a few of the instruments at play here. A great deal of care has been given to this music and it really shows in the end product. Anyone who enjoys good music will find it here.Maybe the best tribute to a musician isn't critical acclaim but emulation by the fans. I've come across sheet music remixes and covers of Mitsuda's work on this album all done by fans as tribute and the desire to perform such music for themselves. This album is good stuff. Frankly I hope Mitsuda makes more.probably some of the best by the fans. I've come across sheet music remixes and covers of Mitsuda's work on this probably some of the best instrumental music I've ever heard. Yasunori Mitsuda incorporates so many instruments and musical styles to this collection it's a real credit to his talent. Guitars violins cellos and the piano are just a few of the instruments at play here. A great deal of care has been given to this music and it really shows in the end product. critical acclaim but emulation by the fans. I've come across sheet music remixes and covers of Mitsuda's work on this probably some of the best instrumental music I've ever heard. Yasunori Mitsuda incorporates so many instruments and musical styles to this collection it's a real credit to his talent. Guitars violins cellos and the piano are just a few of the instruments at play here. A great deal of care has been given to this music and it really shows in the end product. Anyone who enjoys good music will find it here.Maybe the best tribute to a musician isn't critical acclaim but emulation by the fans. I've come across sheet music remixes and covers of Mitsuda's work on this probably some of the best instrumental music I've ever heard. Yasunori Mitsuda incorporates so many instruments and musical styles to this Mitsuda incorporates so many instruments and musical styles to this collection it's a real credit to his talent. Guitars violins cellos and the piano are just a few of the instruments at play here. A great deal of care has been given to this music and it really shows in the end product. Anyone who enjoys good music will find it here.Maybe the best tribute to a musician isn't critical acclaim but emulation by the fans. I've come across sheet music remixes and covers of Mitsuda's work on this";

for(var i=0; i<numRow; i++){

name = people[Math.floor(Math.random()*people.length)];
user_id = Math.floor(Math.random()*totlaCount);
boolean = [true, false][Math.floor(Math.random()*2)];
added_at = new Date();
number = Math.floor(Math.random()*totlaCount);
db.review_collection.save({"name":name, "user_id":user_id, "boolean":
boolean, "added_at":added_at, "number":number, "comment":comment, "comment1":comment, "comment2":comment, "comment3":comment, "comment4":comment, "comment4":comment, "comment5":comment, "comment6":comment, "comment7":comment, "comment8":comment, "comment9":comment, "comment10":comment, "comment11":comment, "comment12":comment, "comment13":comment, "comment14":comment, "comment15":comment, "comment16":comment });
}
